### ISSUE TITLE
Custom card

### ISSUE THREAD

**Issue by TwinMist** [sebbmeyer/php-microsoft-teams-connector#10]
Hi
Is it possible you can show me how to create a custom card?

thanks

**Comment by TwinMist** [comment]
found some info here, worked find, could you add this to our build?

**Comment by gabrielspiteri-highlight** [comment]
Yeah would be awesome to get custom card class here too rather having to pull the laravel package

**Comment by sebbmeyer** [comment]
@gabrielspiteri-highlight what kind of custom card would you like to have?

**Comment by gabrielspiteri-highlight** [comment]
@sebbmeyer https://github.com/sebbmeyer/laravel-teams-connector/blob/master/src/Cards/CustomCard.php this class ... I think it would make sense to be in thie package rather than the laravel one.

**Comment by sebbmeyer** [comment]
ah ok, sure I'm looking into it

**Comment by sebbmeyer** [comment]
@gabrielspiteri-highlight I added the custom card class from the laravel repo and removed all Laravel and PHP 7.x specific syntax. Currently it's still in the branch **feature/custom-card**. Could you do me a favor a test it, because I did not had the time to do it.

**Comment by TwinMist** [comment]
Does the readme instruction need updating?

**Comment by sebbmeyer** [comment]
If everything work as planned, the README would need an update as well.

**Comment by IsaacInsoll** [comment]
<img width="870" alt="Screen Shot 2020-07-29 at 9 19 36 am" src="https://user-images.githubusercontent.com/30609296/88738517-aefa2380-d17c-11ea-8154-8975319c7b86.png">
Hi, 
I've just tried this for a test message and it's working great for me 😀

**Comment by sebbmeyer** [comment]
I updated the readme in that branch and created a pull request (#11). But I'm not 100% sure about some function names, have to think about it. Comments are welcome on the PR

**Comment by IsaacInsoll** [comment]
I just tried adding images to the card today and it didn't work. 
I had to make the following changes for it to work:
![image](https://user-images.githubusercontent.com/30609296/89259221-32c87a00-d66d-11ea-8ed8-60c853d804a9.png)
Sorry, just running out of the office now so didn't have time to do the proper procedures

**Comment by sebbmeyer** [comment]
I checked you code against the documentation and fixed it in the branch (f3b0af01ec24e3a00911a21f844c8cfdd9ac9546). Looks good now

**Comment by sebbmeyer** [comment]
I merged the PR and added a new release (0.1.4)
