### ISSUE TITLE
README example doesn't work on PHP5.6

### ISSUE THREAD

**Issue by kamyweb** [sebbmeyer/php-microsoft-teams-connector#12]
Your package require PHP >5.4 but on PHP5.6 is there a problem on type hinting.
The function setColor, addFactsText, addAction, addFacts, etc... require a "string" but on PHP <7 scalar types are not type-hintable and produce this error:
`Catchable fatal error: Argument 1 passed to Sebbmyr\Teams\Cards\CustomCard::setColor() must be an instance of Sebbmyr\Teams\Cards\string, string given`

**Comment by sebbmeyer** [comment]
seems like I missed that, when I removed the PHP < 7.x specific code. I'll try to fix it soon

**Comment by sebbmeyer** [comment]
@kamyweb sorry for the delay but the problem should now be fixed in 0.1.5
