### ISSUE TITLE
Send() sends message, but returns error

### ISSUE THREAD

**Issue by neologyc** [sebbmeyer/php-microsoft-teams-connector#21]
Hello.

I´m getting error after sending Simple Card. but the message is sent to Teams correctly.

The error is:
`Fatal error: Uncaught Exception: Error response: ok in /data/web/virtuals/91417/virtual/www/****/php/library/vendor/sebbmeyer/php-microsoft-teams-connector/src/TeamsConnector.php:46 Stack trace: #0 /data/web/virtuals/91417/virtual/www/****/php/odkaz.php(190): Sebbmyr\Teams\TeamsConnector->send(Object(Sebbmyr\Teams\Cards\SimpleCard), 20, 10) #1 {main} thrown in /data/web/virtuals/91417/virtual/www/****/php/library/vendor/sebbmeyer/php-microsoft-teams-connector/src/TeamsConnector.php on line 46
`

My code is:

`require_once __DIR__ . '/library/vendor/autoload.php';
$connector = new Sebbmyr\Teams\TeamsConnector('https://teams.szn.cz/hooks/mycorrectincominghookid:-)');
$card  = new \Sebbmyr\Teams\Cards\SimpleCard(['title' => 'Simple card title', 'text' => 
$message]);
// $message contains Markdown code
$connector->send($card ,$timeut = 20, $connectTimeout = 10);`

Totally can´t find the problem.

Thank you for help.

**Comment by k9barry** [comment]
Check the spelling of 

$timeut = 20, 

On Sep 22, 2021, at 6:59 PM, Neologyc ***@***.***> wrote:

﻿
Hello.

I´m getting error after sending Simple Card. but the message is sent to Teams correctly.

The error is:
Fatal error: Uncaught Exception: Error response: ok in /data/web/virtuals/91417/virtual/www/****/php/library/vendor/sebbmeyer/php-microsoft-teams-connector/src/TeamsConnector.php:46 Stack trace: #0 /data/web/virtuals/91417/virtual/www/****/php/odkaz.php(190): Sebbmyr\Teams\TeamsConnector->send(Object(Sebbmyr\Teams\Cards\SimpleCard), 20, 10) #1 {main} thrown in /data/web/virtuals/91417/virtual/www/****/php/library/vendor/sebbmeyer/php-microsoft-teams-connector/src/TeamsConnector.php on line 46

My code is:

require_once __DIR__ . '/library/vendor/autoload.php'; $connector = new Sebbmyr\Teams\TeamsConnector('https://teams.szn.cz/hooks/mycorrectincominghookid:-)'); $card = new \Sebbmyr\Teams\Cards\SimpleCard(['title' => 'Simple card title', 'text' => $message]); // $message contains Markdown code $connector->send($card ,$timeut = 20, $connectTimeout = 10);

Totally can´t find the problem.

Thank you for help.

**Comment by sebbmeyer** [comment]
@neologyc did the code spelling fix solve your problem?

**Comment by sebbmeyer** [comment]
No response, seems to be solved

**Comment by prumpf** [comment]
I am also having this error. 

Here is my code:
```
require __DIR__ . '/vendor/autoload.php';

$connector = new Sebbmyr\Teams\TeamsConnector($url);
$card  = new Sebbmyr\Teams\Cards\SimpleCard(['title' => 'FORM UPDATED', 'text' => 'UPDATED A FORM FOR JANE DOE']);
 
try{
    $connector->send($card);
} catch (Exception $e){
    echo $e->getMessage();
}
```

Output: ```Error Response:```
