### ISSUE TITLE
Unreleased commits

### ISSUE THREAD

**Issue by nenadvasic** [sebbmeyer/php-microsoft-teams-connector#6]
@sebbmeyer , in this repository you have unreleased commits so when you install this package or `laravel-teams-connector`, you get the old version of the code. If everything works ok, you should create a new release.

Thanks! 🍻

**Comment by sebbmeyer** [comment]
@nenadvasic thanks for the hint, I totally forgot to create it. I created a new release 0.1.2, so we do not need to update the laravel package
