### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Benjaminret** [sebbmeyer/php-microsoft-teams-connector#7]
I used, put on production.
I never change code, and now, It does'nt work ...
Did Microsoft change something ?
Thanks

**Comment by sebbmeyer** [comment]
> Did Microsoft change something ?

@Benjaminret It's a possibility that a Teams update can cause troubles with incoming webhooks. Can you check the logs of your application if any errors are thrown as response to the curl call? If not, try to change the webhook url or use another url to check if that could solve the problem.

**Comment by Benjaminret** [comment]
change url. Works :-) but I can't explain ...
